/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Encapsulamiento.EncapsulamientoProducto;
import Negocios.NegociosProducto;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author devilwall
 */
public class BuscarProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form 
     */
    public BuscarProducto() {
        initComponents();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductoTabla = new javax.swing.JTable();
        MenuPrincipal = new javax.swing.JButton();
        BuscarLabel = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        Titulo.setText("Productos:");

        ProductoTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo de Barras", "Nombre", "Descripcion", "Proovedorl", "Piezas", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ProductoTabla);
        if (ProductoTabla.getColumnModel().getColumnCount() > 0) {
            ProductoTabla.getColumnModel().getColumn(0).setMinWidth(0);
            ProductoTabla.getColumnModel().getColumn(0).setPreferredWidth(0);
            ProductoTabla.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        MenuPrincipal.setText("Menu Principal");
        MenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPrincipalActionPerformed(evt);
            }
        });

        BuscarLabel.setText("Buscar");

        TxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarActionPerformed(evt);
            }
        });
        TxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtBuscarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MenuPrincipal)
                        .addGap(30, 30, 30)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BuscarLabel)
                .addGap(13, 13, 13)
                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo)
                    .addComponent(MenuPrincipal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarLabel)
                    .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Limpiar()
    {
       DefaultTableModel ModeloTabla = (DefaultTableModel)ProductoTabla.getModel();

        for(int i = 0; i<ProductoTabla.getRowCount(); i++)
        {
            ModeloTabla.removeRow(i);
            i -=1;
        }
    }
    
    public void Mostrar()
    {
      DefaultTableModel ModeloTabla = (DefaultTableModel)ProductoTabla.getModel();
        
        List<EncapsulamientoProducto> listaProductos = null;
        
        try 
        {
            listaProductos = NegociosProducto.mostrarProductos();
        } 
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex.getMessage());
        }
        
        for(EncapsulamientoProducto productos : listaProductos )
        {
            // Asignamos a un Tipo Object
                       
            Object[] DatosFila =
            {
                productos.ID( ),
                productos.CodigoBarras( ),
                productos.Nombre( ),
                productos.Descripcion( ),
                productos.Proovedor( ),
                productos.Piezas( ),
                productos.Estatus( ),

            };            
            // La propiedad .addRow(Object), requiere un objeto
            ModeloTabla.addRow(DatosFila);
        }
        
        ProductoTabla.setModel(ModeloTabla);

    }


    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Mostrar();
    }//GEN-LAST:event_formInternalFrameOpened

    private void MenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPrincipalActionPerformed
        Menu vistaPrincipal = new Menu();
                JDesktopPane desktopPane = getDesktopPane();
                desktopPane.add(vistaPrincipal);
                vistaPrincipal.setVisible(true); 
                
                this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_MenuPrincipalActionPerformed

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void TxtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarKeyPressed
        // TODO add your handling code here:
            String buscar = (TxtBuscar.getText());
        
        
        DefaultTableModel ModeloTabla = (DefaultTableModel)ProductoTabla.getModel();
        
        List<EncapsulamientoProducto> listaProductos = null;
        
        try 
        {
            Limpiar();
            listaProductos = NegociosProducto.buscarProductos(buscar);
        } 
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "ERROR: " + ex.getMessage());
        }
        
        for(EncapsulamientoProducto productos : listaProductos )
        {
            // Asignamos a un Tipo Object
                       
            Object[] DatosFila =
            {
              productos.ID( ),
                productos.CodigoBarras( ),
                productos.Nombre( ),
                productos.Descripcion( ),
                productos.Proovedor( ),
                productos.Piezas( ),
                productos.Estatus( )
            };            
            // La propiedad .addRow(Object), requiere un objeto
            ModeloTabla.addRow(DatosFila);
        }
        
        ProductoTabla.setModel(ModeloTabla);
        
    }//GEN-LAST:event_TxtBuscarKeyPressed

      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuscarLabel;
    private javax.swing.JButton MenuPrincipal;
    private javax.swing.JTable ProductoTabla;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
